"use client";

import { FormEvent, useEffect, useMemo, useState, useSyncExternalStore } from "react";

type Study = { id:number; type:"오프라인"|"온라인"; date:string; topic:string; speaker:string; detail:string; status:"진행 완료"|"예정" };
type Modal = "login"|"study"|null;

function formatDate(value:string) { const date=new Date(value); const hasTime=!value.endsWith("T00:00"); return `${date.getMonth()+1}월 ${date.getDate()}일 (${["일","월","화","수","목","금","토"][date.getDay()]})${hasTime?` ${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`:" 시간 미정"}`; }
function subscribeMobile(callback:()=>void){const media=window.matchMedia("(max-width: 800px)");media.addEventListener("change",callback);return()=>media.removeEventListener("change",callback);}
function getMobileSnapshot(){return window.matchMedia("(max-width: 800px)").matches;}
function getMobileServerSnapshot(){return false;}

export default function Home() {
  const [studies,setStudies]=useState<Study[]>([]);
  const [admin,setAdmin]=useState(false);
  const [modal,setModal]=useState<Modal>(null);
  const [editing,setEditing]=useState<Study|null>(null);
  const [filter,setFilter]=useState("전체");
  const [query,setQuery]=useState("");
  const [page,setPage]=useState(1);
  const [message,setMessage]=useState("");
  const isMobile=useSyncExternalStore(subscribeMobile,getMobileSnapshot,getMobileServerSnapshot);
  const pageSize=isMobile?5:10;

  function authHeaders(): Record<string,string>{ const token=sessionStorage.getItem("suansa_admin_token"); return token?{authorization:`Bearer ${token}`}:{ }; }
  async function loadStudies(){ const response=await fetch("/api/studies",{cache:"no-store",credentials:"include"}); const data=await response.json(); if(Array.isArray(data.studies)) setStudies(data.studies); }
  useEffect(()=>{ Promise.all([fetch("/api/studies",{cache:"no-store",credentials:"include"}).then(r=>r.json()),fetch("/api/admin",{cache:"no-store",credentials:"include",headers:authHeaders()}).then(r=>r.json())]).then(([studyData,authData])=>{if(Array.isArray(studyData.studies))setStudies(studyData.studies);setAdmin(Boolean(authData.authenticated));}).catch(()=>{}); },[]);

  const visible=useMemo(()=>studies.filter(s=>{ const match=filter==="전체"||s.type===filter||s.status===filter; return match&&`${s.topic} ${s.speaker} ${s.detail}`.toLowerCase().includes(query.toLowerCase()); }).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id),[studies,filter,query]);
  const pageCount=Math.max(1,Math.ceil(visible.length/pageSize));
  const safePage=Math.min(page,pageCount);
  const pagedStudies=visible.slice((safePage-1)*pageSize,safePage*pageSize);

  function openCreate(){ if(!admin){setModal("login");return;} setEditing(null);setModal("study"); }
  function openEdit(study:Study){ setEditing(study);setModal("study"); }

  async function login(event:FormEvent<HTMLFormElement>){ event.preventDefault();setMessage("");const form=new FormData(event.currentTarget);const response=await fetch("/api/admin",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({username:form.get("username"),password:form.get("password")})});const data=await response.json();if(!response.ok){setMessage(data.error??"로그인에 실패했습니다.");return;}if(data.token)sessionStorage.setItem("suansa_admin_token",data.token);const check=await fetch("/api/admin",{cache:"no-store",credentials:"include",headers:authHeaders()}).then(r=>r.json());if(!check.authenticated){setMessage("로그인 정보를 저장하지 못했습니다. 다시 시도해주세요.");return;}setAdmin(true);setModal(null);setMessage(""); }
  async function logout(){ await fetch("/api/admin",{method:"DELETE",credentials:"include",headers:authHeaders()});sessionStorage.removeItem("suansa_admin_token");setAdmin(false);setEditing(null);setModal(null); }

  async function saveStudy(event:FormEvent<HTMLFormElement>){ event.preventDefault();setMessage("");const form=new FormData(event.currentTarget);const payload={id:editing?.id,type:form.get("type"),date:form.get("date"),topic:form.get("topic"),speaker:form.get("speaker"),detail:form.get("detail")};const response=await fetch("/api/studies",{method:editing?"PUT":"POST",credentials:"include",headers:{"content-type":"application/json",...authHeaders()},body:JSON.stringify(payload)});const data=await response.json();if(response.status===401){sessionStorage.removeItem("suansa_admin_token");setAdmin(false);setModal("login");setMessage("로그인이 만료되었습니다. 다시 로그인해주세요.");return;}if(!response.ok){setMessage(data.error??"저장하지 못했습니다.");return;}await loadStudies();setModal(null);setEditing(null); }
  async function removeStudy(study:Study){ if(!confirm(`‘${study.topic}’ 일정을 삭제할까요?`)) return;const response=await fetch(`/api/studies?id=${study.id}`,{method:"DELETE",credentials:"include",headers:authHeaders()});if(response.status===401){sessionStorage.removeItem("suansa_admin_token");setAdmin(false);setModal("login");return;}if(!response.ok){alert("일정을 삭제하지 못했습니다.");return;}setStudies(current=>current.filter(item=>item.id!==study.id)); }

  return <main>
    <header className="topbar"><a className="brand logo-brand" href="#top" aria-label="수안사 홈"><img src="/suansa-logo.png" alt="수안사 - AI를 함께 연구하는 따뜻한 커뮤니티"/></a><nav><a href="#schedule">공식 일정</a><a href="#about">운영 안내</a>{admin?<><span className="admin-badge">관리자</span><button className="quiet" onClick={logout}>로그아웃</button><button className="header-add" onClick={openCreate}><span className="wide-label">+ 일정 등록</span><span className="short-label">+ 등록</span></button></>:<button onClick={()=>setModal("login")}>관리자 로그인</button>}</nav></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">SUANSA · AI STUDY COMMUNITY</p><h1>함께 연구하고,<br/><em>따뜻하게 성장합니다</em></h1><p className="lead">AI를 혼자 배우는 시간을 넘어, 서로의 경험과 생각을 나누며<br className="desktop"/> 실전의 지혜를 함께 쌓아가는 수안사입니다.</p><div className="actions"><a className="primary" href="#schedule">일정 둘러보기 <span>↓</span></a>{admin&&<button className="secondary" onClick={openCreate}>새 일정 등록하기</button>}</div></div><div className="hero-card"><div className="orbit one">✦</div><div className="orbit two">AI</div><div className="logo-stage"><img src="/suansa-logo.png" alt="수안사 로고"/></div><div className="mini-note"><span>STUDY SCHEDULE</span><strong>함께 만드는 배움의 기록</strong><p>관리자가 일정을 안전하게 관리합니다.</p></div></div></section>
    <section className="stats" aria-label="스터디 현황"><div><strong>{studies.length}</strong><span>전체 일정</span></div><div><strong>{studies.filter(s=>s.status==="진행 완료").length}</strong><span>함께한 배움</span></div><div><strong>{new Set(studies.flatMap(s=>s.speaker.split(", "))).size}</strong><span>발제자</span></div><p>수안사의 기록은<br/>계속 이어집니다 <b>→</b></p></section>
    <section className="schedule" id="schedule"><div className="section-head"><div><p className="eyebrow">OFFICIAL SCHEDULE</p><h2>수안사 공식 일정</h2><p>최신 일정부터 {pageSize}개씩 확인하세요.</p></div>{admin&&<button className="primary" onClick={openCreate}>+ 새 일정 등록</button>}</div><div className="tools"><div className="filters">{["전체","예정","오프라인","온라인"].map(item=><button key={item} className={filter===item?"active":""} onClick={()=>{setFilter(item);setPage(1);}}>{item}</button>)}</div><label className="search">⌕<input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="주제, 발제자 검색" aria-label="일정 검색"/></label></div><div className="table-wrap"><table><thead><tr><th>상태</th><th>일정</th><th>주제</th><th>발제자</th><th>내용</th><th>방식</th>{admin&&<th>관리</th>}</tr></thead><tbody>{pagedStudies.map(s=><tr key={s.id}><td><span className={`status ${s.status==="예정"?"upcoming":""}`}>{s.status}</span></td><td className="date">{formatDate(s.date)}</td><td><strong>{s.topic}</strong></td><td><span className="avatar">{s.speaker[0]}</span>{s.speaker}</td><td>{s.detail}</td><td><span className={`type ${s.type==="온라인"?"online":""}`}>{s.type==="온라인"?"◉":"●"} {s.type}</span></td>{admin&&<td><div className="row-actions"><button onClick={()=>openEdit(s)}>수정</button><button className="danger" onClick={()=>removeStudy(s)}>삭제</button></div></td>}</tr>)}</tbody></table>{visible.length===0&&<p className="empty">조건에 맞는 일정이 없습니다.</p>}</div>{visible.length>pageSize&&<nav className="pagination" aria-label="일정 페이지"><button disabled={safePage===1} onClick={()=>setPage(value=>Math.max(1,value-1))}>← 이전</button><span><b>{safePage}</b> / {pageCount}</span><button disabled={safePage===pageCount} onClick={()=>setPage(value=>Math.min(pageCount,value+1))}>다음 →</button></nav>}</section>
    <section className="about" id="about"><div><p className="eyebrow">HOW WE GROW</p><h2>질문은 자유롭게,<br/>성장은 함께.</h2></div><div className="principles"><article><b>01</b><strong>열린 연구</strong><p>새로운 AI 도구와 활용법을 함께 탐구하고 아낌없이 나눕니다.</p></article><article><b>02</b><strong>따뜻한 연결</strong><p>서로의 속도를 존중하며 질문과 경험이 편안하게 오가는 커뮤니티를 만듭니다.</p></article><article><b>03</b><strong>안전한 관리</strong><p>공식 일정은 관리자만 등록·수정·삭제하여 정확한 정보를 유지합니다.</p></article></div></section>
    <footer><div className="brand logo-brand"><img src="/suansa-logo.png" alt="수안사"/></div><p>AI를 함께 연구하는 따뜻한 커뮤니티</p><small>© 2026 SUANSA STUDY. ALL RIGHTS RESERVED.</small></footer>

    {modal&&<div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&(setModal(null),setMessage(""))}><section className="modal" role="dialog" aria-modal="true" aria-label={modal==="login"?"관리자 로그인":"일정 관리"}><button className="close" onClick={()=>{setModal(null);setMessage("");}} aria-label="닫기">×</button>{modal==="login"?<><p className="eyebrow">ADMIN ACCESS</p><h2>관리자 로그인</h2><p>일정 관리 권한이 있는 관리자만 로그인해주세요.</p><form onSubmit={login}><label>아이디<input name="username" autoComplete="username" required autoFocus/></label><label>비밀번호<input name="password" type="password" autoComplete="current-password" required/></label>{message&&<p className="form-error" role="alert">{message}</p>}<button className="primary submit" type="submit">관리자 로그인</button></form></>:<><p className="eyebrow">{editing?"EDIT SCHEDULE":"ADD SCHEDULE"}</p><h2>{editing?"일정 수정":"새 일정 등록"}</h2><p>수안사 공식 일정 정보를 입력해주세요.</p><form onSubmit={saveStudy}><div className="field-row"><label>진행 방식<select name="type" defaultValue={editing?.type??"오프라인"}><option>오프라인</option><option>온라인</option></select></label><label>일정<input name="date" type="datetime-local" required defaultValue={editing?.date}/></label></div><label>주제<input name="topic" required defaultValue={editing?.topic} placeholder="예: 생성형 AI 업무 활용"/></label><label>발제자<input name="speaker" required defaultValue={editing?.speaker} placeholder="이름을 입력하세요"/></label><label>내용<textarea name="detail" required defaultValue={editing?.detail} placeholder="스터디 목적이나 장소, 참고 내용을 입력하세요"/></label>{message&&<p className="form-error" role="alert">{message}</p>}<button className="primary submit" type="submit">{editing?"수정 내용 저장":"공식 일정 등록"}</button><small>저장한 일정은 모든 방문자에게 공개됩니다.</small></form></>}</section></div>}
  </main>;
}
